# Site settings
title: Rath Workshop
SEOTitle: 拉斯工作间 | Rath Workshop
header-img: img/post-bg-desk.jpg
description: " Welcome to RATH Workshop "
keyword: " RATH, 拉斯, 工作间, workshop, rath"
url: "http://batteralter.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Welcome to RATH Workshop"
sidebar-avatar: /img/001.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     fengxiaogang97
zhihu_username:     batteralter




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: SAWAHIRO

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 48323ea517964af584a1                            #生成的clientID
  clientSecret: 77a05f154ac855ee3afd68a84a7dd7660a638d4d    #生成的clientSecret
  repo: BatterAlter.github.io    #仓库名称
  owner: BatterAlter    #github用户名
  admin: BatterAlter
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 5834182ce2ae7baa65745c77d1dc1ca1



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "刀剑神域吧",
        href: "https://tieba.baidu.com/f?fr=wwwt&kw=%E5%88%80%E5%89%91%E7%A5%9E%E5%9F%9F"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    }
]
